[[difmap]]
arch = "i686"
git-tree-sha1 = "4578db2c73481b058f9bbc579984b5bd4243003b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "7e419e902bd34599586af352d8f363414d4a4d023a17f3b88b933a85f774b633"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.i686-linux-gnu-libgfortran3.tar.gz"
[[difmap]]
arch = "i686"
git-tree-sha1 = "24385571811e2f7661c2b5c1d5b18c6948feac19"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "e16bc73e270f2def0d2b9b07af195ad2508bc4d9beb2725c1a0cc4d348ff38da"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.i686-linux-gnu-libgfortran4.tar.gz"
[[difmap]]
arch = "i686"
git-tree-sha1 = "21f6af05c24dcd7d397610d89397f6d191481fd4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "2b3db94332c7d674e07441b14158dca433265623b7b76362a0b4e35f937bad76"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.i686-linux-gnu-libgfortran5.tar.gz"
[[difmap]]
arch = "x86_64"
git-tree-sha1 = "b13b5a34ad3f7789a5dc93b6cf27d62a720b8c03"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "43650c4570b35114b2eccdc299fc962beb34c6b1b31b23c26bf6bf645f31e4c2"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.x86_64-linux-gnu-libgfortran3.tar.gz"
[[difmap]]
arch = "x86_64"
git-tree-sha1 = "40e6f0cac970565eb4a9dc765931ed8eb8623072"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "f6c6071411679e6c9f444a23db1f4ec6cf7cd26696d2fd158008f1f1667d52ec"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.x86_64-linux-gnu-libgfortran4.tar.gz"
[[difmap]]
arch = "x86_64"
git-tree-sha1 = "b31ced1086ef1793831a8dc02d37977b25917eee"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "3bae14b7303fce8346b05e4a9cbef3abfeadf274c390ebd96150ca298764b368"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.x86_64-linux-gnu-libgfortran5.tar.gz"
[[difmap]]
arch = "x86_64"
git-tree-sha1 = "15613e14adf779c036868e2ed0007ee1fe2ca15e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "4823a357d057ff428990f5e27cbcfe40c496a59efb28e16705ac76b366dd524d"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.x86_64-linux-musl-libgfortran3.tar.gz"
[[difmap]]
arch = "x86_64"
git-tree-sha1 = "8b6cc0d879a475a97cab36f03c9259fdd8e5fd52"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "b6974355abba8ed4afc41442e5ad298ff8104169ce92e1b7e8d0a88614d7036b"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.x86_64-linux-musl-libgfortran4.tar.gz"
[[difmap]]
arch = "x86_64"
git-tree-sha1 = "b123257c218d52f2ee992548ebc3f2f2d4bc8302"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[difmap.download]]
    sha256 = "2b6cd59a1a2541e06392bcff535c99896b3456e08438b0043c6fd448f24cff99"
    url = "https://github.com/JuliaBinaryWrappers/difmap_jll.jl/releases/download/difmap-v2.5.11+0/difmap.v2.5.11.x86_64-linux-musl-libgfortran5.tar.gz"
